version: '3.8'

services:
  mysql:
    image: mysql:8.1
    container_name: local-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: security_applications_demo
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "6603:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
    driver: local
