# Use Eclipse Temurin as the base image
FROM eclipse-temurin:latest

# Set the working directory inside the container
WORKDIR /app

# Copy the jar file to the container
COPY target/micro-visualizer-0.0.1-SNAPSHOT.jar micro-visualizer.jar

# Run the jar file
ENTRYPOINT ["java", "-jar", "-Dspring.profiles.active=k8s", "micro-visualizer.jar"]