apiVersion: apps/v1
kind: Deployment
metadata:
  name: virtual-topic-publisher-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: virtual-topic-publisher
  template:
    metadata:
      labels:
        app: virtual-topic-publisher
    spec:
      containers:
        - name: virtual-topic-publisher
          image: virtual-topic-publisher-app
          imagePullPolicy: Never #use local image