global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'micro-sender'
    static_configs:
      - targets: ['micro-sender:8080']
    metrics_path: '/actuator/prometheus'

  - job_name: 'micro-recipient'
    static_configs:
      - targets: ['micro-recipient:8080']
    metrics_path: '/actuator/prometheus'

  - job_name: 'micro-collector'
    static_configs:
      - targets: ['micro-collector:8080']
    metrics_path: '/actuator/prometheus'

  - job_name: 'micro-visualizer'
    static_configs:
      - targets: ['micro-visualizer:8080']
    metrics_path: '/actuator/prometheus'