version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    network_mode: host  # Use host network mode to communicate directly with host services
    ports:
      - "80:80"  # Map port 80 of the container to port 80 of the host => For HTTP 1.1 in demo
      - "443:443"  # If you want to add HTTPS, HTTP/2 HTTP/3 later => For HTTP/2 in demo
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Mount the custom nginx.conf to the container
      - ./certs:/etc/nginx/certs:ro  # Mount the SSL certificates to the container

networks:
  springboot_network:
    driver: bridge