global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['recipient:8080', 'collector:8080', 'sender:8080']
    metrics_path: '/actuator/prometheus'