apiVersion: apps/v1
kind: Deployment
metadata:
  name: activemq-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: activemq
  template:
    metadata:
      labels:
        app: activemq
    spec:
      containers:
        - name: activemq
          image: rmohr/activemq
          ports:
            - containerPort: 61616
            - containerPort: 8161
---
apiVersion: v1
kind: Service
metadata:
  name: activemq-service
spec:
  selector:
    app: activemq
  ports:
    - name: message-broker   # Name for the ActiveMQ message broker port
      protocol: TCP
      port: 61616        # Port for ActiveMQ message broker
      targetPort: 61616   # Target port inside the container for ActiveMQ message broker
    - name: web-console       # Name for the ActiveMQ web console port
      protocol: TCP
      port: 8161         # Port for ActiveMQ Web Console (Dashboard)
      targetPort: 8161    # Target port inside the container for the web console
  type: LoadBalancer # make it as loadbalancer, so minikube tunnel can expose this service to my localhost
