apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-recipient-v2
  labels:
    app: micro-recipient
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micro-recipient
      version: v2
  template:
    metadata:
      labels:
        app: micro-recipient
        version: v2
    spec:
      containers:
        - name: micro-recipient
          image: ljx213101212/micro-recipient-k8s:a_b_testing_v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: "prometheus,health,info"
            - name: MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED
              value: "true"
            - name: MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS
              value: "always"
---
apiVersion: v1
kind: Service
metadata:
  name: micro-recipient-v2
  labels:
    app: micro-recipient
spec:
  ports:
    - port: 8080
  selector:
    app: micro-recipient
